### ISSUE TITLE
Error on bitbucket: Unauthorized Authentication failed: query hash does not match

### ISSUE THREAD

**Issue by sreeramk08** [mibexsoftware/sonar-bitbucket-plugin#84]
### Expected Behavior

The bitbucket overview page should not have this error.

### Actual Behavior

Getting a Unauthorized Authentication failed: query hash does not match.  It tries to load a page called ch.mibex.sonar.bitbucket and cannot.  I tried removing the integration for sonar.bitbucket cloud and still this appears.  I have shut down the sonarqube server and still no use.   

Source code is not showing up properly either.  
 
### Plug-in version, SonarQube version, CI system, build type
Plugin version 1.2.3
Sonarqube: 6.1
CI: Jenkins

**Comment by trustlix** [comment]
Seeing the same error here

**Comment by montrin** [comment]
Hi

We are investigating the issue.

What do you mean by “Source code is not showing up properly either.“? Could you send me a link / screenshot?

Thanks
Monica

**Comment by sreeramk08** [comment]
Hi

   The issue was resolved when I removed the 'sonar for bitbucket cloud' integration from bitbucket.  But I had added the integration almost a year back.  Why did it start failing this week?  Was the herokuapp down?

________________________________

**Comment by sreeramk08** [comment]
And to answer your question about source code...when the issue was there, if we click on 'Source' and look at the Branches list, the list was incomplete.  We could not find some branches.  And these were not some old branches...these were ones that checkin was happening daily.
________________________________

**Comment by montrin** [comment]
Hi

It's working again. Could you please try? Otherwise please re-open the issue.

Thanks
Monica

**Comment by trustlix** [comment]
The error message changed... but still not working for me:

![selection_144](https://user-images.githubusercontent.com/530756/39770961-f8c59cf6-52c6-11e8-9497-6b4cd2652ab4.png)

**Comment by mrueegg** [comment]
@trustlix Thanks for your feedback. Please note that the access to SonarQube happens from our add-on (and not from Bitbucket) which is hosted on Heroku. You would therefore have to whitelist the IPs from Heroku. You can find more information here (https://help.heroku.com/JS13Y78I/i-need-to-whitelist-heroku-dynos-what-are-ip-address-ranges-in-use-at-heroku). Hope this helps. If yes, I would like to kindly ask you to revise your Marketplace app feedback :-) Thanks!

**Comment by trustlix** [comment]
Got it! Thanks!
